/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as ConvertLib from '../test/generated-artifacts/ConvertLib.json';
import * as IERC20 from '../test/generated-artifacts/IERC20.json';
import * as IStructs from '../test/generated-artifacts/IStructs.json';
import * as LibFixedMath from '../test/generated-artifacts/LibFixedMath.json';
import * as LibSafeMath from '../test/generated-artifacts/LibSafeMath.json';
import * as LibScamMath from '../test/generated-artifacts/LibScamMath.json';
import * as Liquidity from '../test/generated-artifacts/Liquidity.json';
import * as Migrations from '../test/generated-artifacts/Migrations.json';
import * as Scam from '../test/generated-artifacts/Scam.json';
import * as State from '../test/generated-artifacts/State.json';
import * as Swapper from '../test/generated-artifacts/Swapper.json';
import * as TestLibScamMath from '../test/generated-artifacts/TestLibScamMath.json';
export const artifacts = {
    ConvertLib: ConvertLib as ContractArtifact,
    Migrations: Migrations as ContractArtifact,
    Scam: Scam as ContractArtifact,
    Liquidity: Liquidity as ContractArtifact,
    State: State as ContractArtifact,
    Swapper: Swapper as ContractArtifact,
    IERC20: IERC20 as ContractArtifact,
    IStructs: IStructs as ContractArtifact,
    LibFixedMath: LibFixedMath as ContractArtifact,
    LibSafeMath: LibSafeMath as ContractArtifact,
    LibScamMath: LibScamMath as ContractArtifact,
    TestLibScamMath: TestLibScamMath as ContractArtifact,
};
