/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as IERC20 from '../test/generated-artifacts/IERC20.json';
import * as IEvents from '../test/generated-artifacts/IEvents.json';
import * as IStructs from '../test/generated-artifacts/IStructs.json';
import * as LibFixedMath from '../test/generated-artifacts/LibFixedMath.json';
import * as LibSafeMath from '../test/generated-artifacts/LibSafeMath.json';
import * as LibScamMath from '../test/generated-artifacts/LibScamMath.json';
import * as LibToken from '../test/generated-artifacts/LibToken.json';
import * as Liquidity from '../test/generated-artifacts/Liquidity.json';
import * as Ownable from '../test/generated-artifacts/Ownable.json';
import * as Scam from '../test/generated-artifacts/Scam.json';
import * as State from '../test/generated-artifacts/State.json';
import * as Swapper from '../test/generated-artifacts/Swapper.json';
import * as TestLibScamMath from '../test/generated-artifacts/TestLibScamMath.json';
import * as TestScam from '../test/generated-artifacts/TestScam.json';
import * as UnitTestScam from '../test/generated-artifacts/UnitTestScam.json';
export const artifacts = {
    Scam: Scam as ContractArtifact,
    Liquidity: Liquidity as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    State: State as ContractArtifact,
    Swapper: Swapper as ContractArtifact,
    IERC20: IERC20 as ContractArtifact,
    IEvents: IEvents as ContractArtifact,
    IStructs: IStructs as ContractArtifact,
    LibFixedMath: LibFixedMath as ContractArtifact,
    LibSafeMath: LibSafeMath as ContractArtifact,
    LibScamMath: LibScamMath as ContractArtifact,
    LibToken: LibToken as ContractArtifact,
    TestLibScamMath: TestLibScamMath as ContractArtifact,
    TestScam: TestScam as ContractArtifact,
    UnitTestScam: UnitTestScam as ContractArtifact,
};
