/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as IERC20 from '../test/generated-artifacts/IERC20.json';
import * as IEvents from '../test/generated-artifacts/IEvents.json';
import * as IStructs from '../test/generated-artifacts/IStructs.json';
import * as LibAMM from '../test/generated-artifacts/LibAMM.json';
import * as LibBondingCurve from '../test/generated-artifacts/LibBondingCurve.json';
import * as LibConstants from '../test/generated-artifacts/LibConstants.json';
import * as LibFixedMath from '../test/generated-artifacts/LibFixedMath.json';
import * as LibRootFinding from '../test/generated-artifacts/LibRootFinding.json';
import * as LibSafeMath from '../test/generated-artifacts/LibSafeMath.json';
import * as LibToken from '../test/generated-artifacts/LibToken.json';
import * as Liquidity from '../test/generated-artifacts/Liquidity.json';
import * as Ownable from '../test/generated-artifacts/Ownable.json';
import * as Scam from '../test/generated-artifacts/Scam.json';
import * as State from '../test/generated-artifacts/State.json';
import * as UnitTestScam from '../test/generated-artifacts/UnitTestScam.json';
export const artifacts = {
    Scam: Scam as ContractArtifact,
    Liquidity: Liquidity as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    State: State as ContractArtifact,
    IERC20: IERC20 as ContractArtifact,
    IEvents: IEvents as ContractArtifact,
    IStructs: IStructs as ContractArtifact,
    LibAMM: LibAMM as ContractArtifact,
    LibBondingCurve: LibBondingCurve as ContractArtifact,
    LibConstants: LibConstants as ContractArtifact,
    LibFixedMath: LibFixedMath as ContractArtifact,
    LibRootFinding: LibRootFinding as ContractArtifact,
    LibSafeMath: LibSafeMath as ContractArtifact,
    LibToken: LibToken as ContractArtifact,
    UnitTestScam: UnitTestScam as ContractArtifact,
};
