/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../test/generated-wrappers/fixidity_lib';
export * from '../test/generated-wrappers/i_events';
export * from '../test/generated-wrappers/i_structs';
export * from '../test/generated-wrappers/ierc20';
export * from '../test/generated-wrappers/lib_fixed_math';
export * from '../test/generated-wrappers/lib_safe_math';
export * from '../test/generated-wrappers/lib_scam_math';
export * from '../test/generated-wrappers/liquidity';
export * from '../test/generated-wrappers/logarithm_lib';
export * from '../test/generated-wrappers/scam';
export * from '../test/generated-wrappers/state';
export * from '../test/generated-wrappers/swapper';
export * from '../test/generated-wrappers/test_lib_scam_math';
export * from '../test/generated-wrappers/test_scam';
