/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as Scam from '../generated-artifacts/Scam.json';
import * as UnitTestScam from '../generated-artifacts/UnitTestScam.json';
export const artifacts = {Scam: Scam as ContractArtifact, UnitTestScam: UnitTestScam as ContractArtifact};
