/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import {ContractArtifact} from 'ethereum-types';

import * as UnitTest from '../generated-artifacts/UnitTest.json';
export const artifacts = {UnitTest: UnitTest as ContractArtifact};
